-- MySQL Script generated by MySQL Workbench
-- Wed Nov 19 21:59:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Eccomerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Eccomerce` ;

-- -----------------------------------------------------
-- Schema Eccomerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Eccomerce` DEFAULT CHARACTER SET utf8 ;
USE `Eccomerce` ;

-- -----------------------------------------------------
-- Table `Eccomerce`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Eccomerce`.`Category` ;

CREATE TABLE IF NOT EXISTS `Eccomerce`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Eccomerce`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Eccomerce`.`Customers` ;

CREATE TABLE IF NOT EXISTS `Eccomerce`.`Customers` (
  `idCustomers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomers`))
ENGINE = InnoDB
AUTO_INCREMENT = 105
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Eccomerce`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Eccomerce`.`Orders` ;

CREATE TABLE IF NOT EXISTS `Eccomerce`.`Orders` (
  `idOrders` INT NOT NULL AUTO_INCREMENT,
  `Customers_idCustomers` INT NOT NULL,
  `OrderDate` DATETIME NOT NULL,
  `TotalAmount` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idOrders`),
  INDEX `fk_Orders_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `Eccomerce`.`Customers` (`idCustomers`))
ENGINE = InnoDB
AUTO_INCREMENT = 248
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Eccomerce`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Eccomerce`.`Products` ;

CREATE TABLE IF NOT EXISTS `Eccomerce`.`Products` (
  `idProducts` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Price` DECIMAL(10,2) NULL DEFAULT NULL,
  `Stock` INT NULL DEFAULT NULL,
  `Category_idCategory` INT NOT NULL,
  PRIMARY KEY (`idProducts`),
  INDEX `fk_Products_Category_idx` (`Category_idCategory` ASC) VISIBLE,
  CONSTRAINT `fk_Products_Category`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `Eccomerce`.`Category` (`idCategory`))
ENGINE = InnoDB
AUTO_INCREMENT = 251
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Eccomerce`.`OrderDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Eccomerce`.`OrderDetails` ;

CREATE TABLE IF NOT EXISTS `Eccomerce`.`OrderDetails` (
  `idOrderDetails` INT NOT NULL AUTO_INCREMENT,
  `Orders_idOrders` INT NOT NULL,
  `Products_idProducts` INT NOT NULL,
  `Quantity` INT NULL DEFAULT NULL,
  `SubTotal` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`idOrderDetails`),
  INDEX `fk_OrderDetails_Orders1_idx` (`Orders_idOrders` ASC) VISIBLE,
  INDEX `fk_OrderDetails_Products1_idx` (`Products_idProducts` ASC) VISIBLE,
  CONSTRAINT `fk_OrderDetails_Orders1`
    FOREIGN KEY (`Orders_idOrders`)
    REFERENCES `Eccomerce`.`Orders` (`idOrders`),
  CONSTRAINT `fk_OrderDetails_Products1`
    FOREIGN KEY (`Products_idProducts`)
    REFERENCES `Eccomerce`.`Products` (`idProducts`))
ENGINE = InnoDB
AUTO_INCREMENT = 2619
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
