USE Eccomerce;

INSERT INTO Category (idCategory, Name) VALUES
(1, 'Electronics'),
(2, 'Clothing'),
(3, 'Books'),
(4, 'Home & Kitchen'),
(5, 'Beauty'),
(6, 'Sports'),
(7, 'Gaming'),
(8, 'Office Supplies'),
(9, 'Automotive'),
(10, 'Toys');


/*Customers*/
INSERT INTO Customers (idCustomers, Name, Email) VALUES
(1, 'Alice Carter', 'alice1@example.com'),
(2, 'Bob Ramirez', 'bob2@example.com'),
(3, 'Charlie Mendoza', 'charlie3@example.com'),
(4, 'Diana Lopez', 'diana4@example.com'),
(5, 'Ethan Smith', 'ethan5@example.com'),
(6, 'Fiona Johnson', 'fiona6@example.com'),
(7, 'George Perez', 'george7@example.com'),
(8, 'Hannah Davis', 'hannah8@example.com'),
(9, 'Ian Wilson', 'ian9@example.com'),
(10, 'Julia Thompson', 'julia10@example.com'),
(11, 'Kevin Martinez', 'kevin11@example.com'),
(12, 'Laura Clark', 'laura12@example.com'),
(13, 'Marco Torres', 'marco13@example.com'),
(14, 'Nina Sanchez', 'nina14@example.com'),
(15, 'Oscar Rivera', 'oscar15@example.com'),
(16, 'Paula Gomez', 'paula16@example.com'),
(17, 'Quentin Flores', 'quentin17@example.com'),
(18, 'Rita Ortiz', 'rita18@example.com'),
(19, 'Samuel Hughes', 'sam19@example.com'),
(20, 'Tina Brooks', 'tina20@example.com'),
(21, 'Ulysses Reed', 'ulysses21@example.com'),
(22, 'Violet Jenkins', 'violet22@example.com'),
(23, 'Walter Morales', 'walter23@example.com'),
(24, 'Ximena Ruiz', 'ximena24@example.com'),
(25, 'Yara Delgado', 'yara25@example.com'),
(26, 'Zack Alvarez', 'zack26@example.com'),
(27, 'Bella Rivera', 'bella27@example.com'),
(28, 'Carlos Mendoza', 'carlos28@example.com'),
(29, 'Daniela Castro', 'daniela29@example.com'),
(30, 'Eduardo Rivas', 'eduardo30@example.com'),
(31, 'Fernanda Navarro', 'fernanda31@example.com'),
(32, 'Gabriel Soto', 'gabriel32@example.com'),
(33, 'Helena Duarte', 'helena33@example.com'),
(34, 'Ismael Peña', 'ismael34@example.com'),
(35, 'Jorge Salazar', 'jorge35@example.com'),
(36, 'Karen Vega', 'karen36@example.com'),
(37, 'Luis Contreras', 'luis37@example.com'),
(38, 'Mia Escobar', 'mia38@example.com'),
(39, 'Noah Marquez', 'noah39@example.com'),
(40, 'Olivia Tellez', 'olivia40@example.com'),
(41, 'Pedro Grijalva', 'pedro41@example.com'),
(42, 'Queen Soto', 'queen42@example.com'),
(43, 'Raul Ortega', 'raul43@example.com'),
(44, 'Sara Pineda', 'sara44@example.com'),
(45, 'Thiago Luna', 'thiago45@example.com'),
(46, 'Uriel Quintero', 'uriel46@example.com'),
(47, 'Valeria Tapia', 'valeria47@example.com'),
(48, 'William Cifuentes', 'william48@example.com'),
(49, 'Xavier Ponce', 'xavier49@example.com'),
(50, 'Yuliana Palma', 'yuliana50@example.com'),
(51, 'Andy Torres', 'andy51@example.com'),
(52, 'Brenda Lozano', 'brenda52@example.com'),
(53, 'Cristian Pardo', 'cristian53@example.com'),
(54, 'Dalia Guerrero', 'dalia54@example.com'),
(55, 'Erick Orellana', 'erick55@example.com'),
(56, 'Fatima Reyes', 'fatima56@example.com'),
(57, 'Giovanni Ibarra', 'giovanni57@example.com'),
(58, 'Hazel Molina', 'hazel58@example.com'),
(59, 'Ivan Campos', 'ivan59@example.com'),
(60, 'Janeth Mena', 'janeth60@example.com'),
(61, 'Karla Zuñiga', 'karla61@example.com'),
(62, 'Leonardo Caal', 'leonardo62@example.com'),
(63, 'Mariela Xoy', 'mariela63@example.com'),
(64, 'Nicolas Aj', 'nicolas64@example.com'),
(65, 'Olga Tuy', 'olga65@example.com'),
(66, 'Pablo Yoc', 'pablo66@example.com'),
(67, 'Quincy Najera', 'quincy67@example.com'),
(68, 'Roxana Pec', 'roxana68@example.com'),
(69, 'Sergio Cutz', 'sergio69@example.com'),
(70, 'Tadeo Pop', 'tadeo70@example.com'),
(71, 'Ursula Choc', 'ursula71@example.com'),
(72, 'Vanessa Cux', 'vanessa72@example.com'),
(73, 'Wendy Ux', 'wendy73@example.com'),
(74, 'Xenia Lux', 'xenia74@example.com'),
(75, 'Yordi Tzoc', 'yordi75@example.com'),
(76, 'Zulma Ixcamparij', 'zulma76@example.com'),
(77, 'Allan Tziquin', 'allan77@example.com'),
(78, 'Brayan Iboy', 'brayan78@example.com'),
(79, 'Cesar Shol', 'cesar79@example.com'),
(80, 'Damaris Pop', 'damaris80@example.com'),
(81, 'Edgar Coh', 'edgar81@example.com'),
(82, 'Felipe Tzaj', 'felipe82@example.com'),
(83, 'German Tiul', 'german83@example.com'),
(84, 'Heidy Paau', 'heidy84@example.com'),
(85, 'Ingrid Tuy', 'ingrid85@example.com'),
(86, 'Jairo Cutzal', 'jairo86@example.com'),
(87, 'Kenny Cutzal', 'kenny87@example.com'),
(88, 'Lizeth Chub', 'lizeth88@example.com'),
(89, 'Milton Cux', 'milton89@example.com'),
(90, 'Nadia Xol', 'nadia90@example.com'),
(91, 'Omar Caal', 'omar91@example.com'),
(92, 'Patricia Ixquiac', 'patricia92@example.com'),
(93, 'Rudy Cox', 'rudy93@example.com'),
(94, 'Sandra Aj', 'sandra94@example.com'),
(95, 'Tomy Ixpatá', 'tomy95@example.com'),
(96, 'Ulises Cho', 'ulises96@example.com'),
(97, 'Victor Xiloj', 'victor97@example.com'),
(98, 'Wilder Coxol', 'wilder98@example.com'),
(99, 'Xavier Pop', 'xavier99@example.com'),
(100, 'Yessica Lux', 'yessica100@example.com');

